// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wallet.Infrastructure.Persistence;

#nullable disable

namespace Wallet.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260706113432_AddExchangeRate")]
    partial class AddExchangeRate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Wallet.Domain.Transfers.Transfer", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<DateTimeOffset?>("CompletedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte[]>("DestinationWalletId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<decimal>("ExchangeRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset?>("FailedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<byte[]>("SourceWalletId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("StatusId");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id")
                        .HasName("pk_transfers");

                    b.HasIndex("CreatedOnUtc");

                    b.HasIndex("DestinationWalletId");

                    b.HasIndex("SourceWalletId");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("Transfers", (string)null);
                });

            modelBuilder.Entity("Wallet.Domain.Wallets.Wallet", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Currency")
                        .HasColumnType("int")
                        .HasColumnName("CurrencyId");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id")
                        .HasName("pk_wallets");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Currency")
                        .IsUnique();

                    b.ToTable("Wallets", (string)null);
                });

            modelBuilder.Entity("Wallet.Domain.Wallets.WalletTransaction", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("StatusId");

                    b.Property<byte[]>("TransferId")
                        .HasColumnType("binary(16)");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("TypeId");

                    b.Property<byte[]>("WalletId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.HasKey("Id")
                        .HasName("pk_wallet_transaction");

                    b.HasIndex("CreatedOnUtc");

                    b.HasIndex("TransferId");

                    b.HasIndex("WalletId");

                    b.HasIndex("WalletId", "OperationId")
                        .IsUnique()
                        .HasDatabaseName("uq_wallet_transactions_wallet_id_operation_id");

                    b.ToTable("WalletTransactions", (string)null);
                });

            modelBuilder.Entity("Wallet.Domain.Transfers.Transfer", b =>
                {
                    b.OwnsOne("Wallet.Domain.Shared.Money", "Money", b1 =>
                        {
                            b1.Property<byte[]>("TransferId")
                                .HasColumnType("binary(16)");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Amount");

                            b1.Property<int>("Currency")
                                .HasColumnType("int")
                                .HasColumnName("CurrencyId");

                            b1.HasKey("TransferId");

                            b1.ToTable("Transfers");

                            b1.WithOwner()
                                .HasForeignKey("TransferId");
                        });

                    b.Navigation("Money")
                        .IsRequired();
                });

            modelBuilder.Entity("Wallet.Domain.Wallets.WalletTransaction", b =>
                {
                    b.HasOne("Wallet.Domain.Wallets.Wallet", null)
                        .WithMany("Transactions")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.OwnsOne("Wallet.Domain.Shared.Money", "Money", b1 =>
                        {
                            b1.Property<byte[]>("WalletTransactionId")
                                .HasColumnType("binary(16)");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Amount");

                            b1.Property<int>("Currency")
                                .HasColumnType("int")
                                .HasColumnName("CurrencyId");

                            b1.HasKey("WalletTransactionId");

                            b1.ToTable("WalletTransactions");

                            b1.WithOwner()
                                .HasForeignKey("WalletTransactionId");
                        });

                    b.Navigation("Money")
                        .IsRequired();
                });

            modelBuilder.Entity("Wallet.Domain.Wallets.Wallet", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
